const state={pages:JSON.parse(localStorage.getItem('aegisPages')||'null')||[{id:crypto.randomUUID(),name:'Home',sections:[{id:crypto.randomUUID(),type:'hero',title:'Welcome to Aegis Institute',text:'Education, consulting and community support.',button:'Get started'},{id:crypto.randomUUID(),type:'text',title:'Built for your community',text:'Edit this page using the builder. Add sections, change colours, and publish your own content.'}]}],settings:JSON.parse(localStorage.getItem('aegisSettings')||'null')||{title:'Aegis Institute',logo:'',favicon:'',primary:'#1d4ed8',background:'#f4f7fb',text:'#172033'},currentPage:0,selected:null};
const $=s=>document.querySelector(s);
function save(){localStorage.setItem('aegisPages',JSON.stringify(state.pages));localStorage.setItem('aegisSettings',JSON.stringify(state.settings));}
function renderPages(){const list=$('#pageList');list.innerHTML='';state.pages.forEach((p,i)=>{const el=document.createElement('div');el.className='page-item '+(i===state.currentPage?'active':'');el.textContent=p.name;el.onclick=()=>{state.currentPage=i;state.selected=null;render()};list.appendChild(el)})}
function sectionHTML(s){if(s.type==='hero')return `<h2>${esc(s.title)}</h2><p>${esc(s.text)}</p>${s.button?`<button class="primary">${esc(s.button)}</button>`:''}`;if(s.type==='text')return `<h2>${esc(s.title)}</h2><p>${esc(s.text)}</p>`;if(s.type==='image')return `<h2>${esc(s.title)}</h2>${s.url?`<img src="${esc(s.url)}" alt="">`: '<p class="muted">Add an image URL in the editor.</p>'}`;if(s.type==='cards')return `<h2>${esc(s.title)}</h2><div class="cards-grid">${s.cards.map(c=>`<div class="card"><strong>${esc(c.title)}</strong><p>${esc(c.text)}</p></div>`).join('')}</div>`;return `<h2>${esc(s.title)}</h2><button class="primary">${esc(s.button||'Button')}</button>`}
function renderCanvas(){const page=state.pages[state.currentPage];$('#currentPageTitle').textContent=page.name;const canvas=$('#canvas');canvas.innerHTML='';page.sections.forEach((s,i)=>{const el=document.createElement('section');el.className='section '+s.type+'-section '+(state.selected===s.id?'selected':'');el.innerHTML=`<div class="section-toolbar"><button data-up="${i}">↑</button><button data-down="${i}">↓</button><button data-remove="${i}">Delete</button></div>${sectionHTML(s)}`;el.onclick=e=>{if(e.target.closest('.section-toolbar'))return;state.selected=s.id;renderInspector();renderCanvas()};canvas.appendChild(el)});}
function renderInspector(){const box=$('#inspectorContent'),s=state.pages[state.currentPage].sections.find(x=>x.id===state.selected);if(!s){box.textContent='Select a section to edit it.';return}box.innerHTML=`<label>Title<input id="editTitle" value="${esc(s.title||'')}"></label><label>Text<textarea id="editText">${esc(s.text||'')}</textarea></label>${s.type==='image'?'<label>Image URL<input id="editUrl" value="'+esc(s.url||'')+'"></label>':''}${s.type==='hero'||s.type==='button'?'<label>Button text<input id="editButton" value="'+esc(s.button||'')+'"></label>':''}<button id="applyElement" class="primary full">Apply changes</button>`;$('#applyElement').onclick=()=>{s.title=$('#editTitle').value;s.text=$('#editText').value;if($('#editUrl'))s.url=$('#editUrl').value;if($('#editButton'))s.button=$('#editButton').value;save();render()}}
function render(){renderPages();renderCanvas();renderInspector();$('#siteTitle').value=state.settings.title;$('#logoUrl').value=state.settings.logo;$('#faviconUrl').value=state.settings.favicon;$('#primaryColor').value=state.settings.primary;$('#backgroundColor').value=state.settings.background;$('#textColor').value=state.settings.text}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelectorAll('.side-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.panel+'Panel').classList.remove('hidden')});
$('#newPageButton').onclick=()=>{const name=prompt('Page name');if(name){state.pages.push({id:crypto.randomUUID(),name,sections:[]});state.currentPage=state.pages.length-1;save();render()}};
document.querySelectorAll('.add-section').forEach(b=>b.onclick=()=>{const type=b.dataset.type;const defaults={hero:{title:'New hero section',text:'Add your message here.',button:'Learn more'},text:{title:'New text section',text:'Write your content here.'},image:{title:'Image section',url:''},cards:{title:'Featured cards',cards:[{title:'Card one',text:'Description'},{title:'Card two',text:'Description'}]},button:{title:'Call to action',button:'Click here'}};state.pages[state.currentPage].sections.push({id:crypto.randomUUID(),type,...defaults[type]});save();render()});
$('#applySettings').onclick=()=>{state.settings={title:$('#siteTitle').value,logo:$('#logoUrl').value,favicon:$('#faviconUrl').value,primary:$('#primaryColor').value,background:$('#backgroundColor').value,text:$('#textColor').value};document.documentElement.style.setProperty('--primary',state.settings.primary);save();render()};
$('#publishButton').onclick=()=>{save();alert('Changes saved locally. Connect the Cloudflare Worker to publish to D1.')};
$('#logoutButton').onclick=()=>{sessionStorage.removeItem('aegisAuthenticated');location.href='login.html'};
$('#previewButton').onclick=()=>{const overlay=document.createElement('div');overlay.className='preview-frame';overlay.innerHTML='<button class="preview-close primary">Close preview</button><div class="preview-content">'+$('#canvas').innerHTML+'</div>';overlay.querySelector('.preview-close').onclick=()=>overlay.remove();document.body.appendChild(overlay)};
$('#deletePageButton').onclick=()=>{if(state.pages.length===1)return alert('You need at least one page.');if(confirm('Delete this page?')){state.pages.splice(state.currentPage,1);state.currentPage=0;save();render()}};
if(sessionStorage.getItem('aegisAuthenticated')!=='true')location.href='login.html';render();
