CREATE TABLE IF NOT EXISTS sites (id TEXT PRIMARY KEY, title TEXT NOT NULL, settings TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pages (id TEXT PRIMARY KEY, site_id TEXT NOT NULL, name TEXT NOT NULL, content TEXT NOT NULL, updated_at TEXT NOT NULL);
